CREATE TABLE "GCG_6005_MATREQ_Q" (
 "EMPLOYEE" CHAR(5),
 "PART" CHAR(20),
 "LOCATION" CHAR(2),
 "QTY_REQ" DOUBLE,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "DATE_REQ" DATE,
 "TIME_REQ" DATETIME,
 "ORIGIN_REQ" LONGVARCHAR,
 "USE_GL" BIT NOT NULL,
 "GL_ACCOUNT" CHAR(15) );